# Generated by Django 4.0.1 on 2022-01-29 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_quiz_groups_remove_quiz_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='quiz_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
