# Generated by Django 4.0.1 on 2022-01-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='report_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
            preserve_default=False,
        ),
    ]
