# Generated by Django 4.0.1 on 2022-01-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='report_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.reportanswer'),
            preserve_default=False,
        ),
    ]
